# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Canonical Ltd.

name: Master workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build

  env-print:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Print env
        run: go version
        
  docker-build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          
      - uses: docker/setup-buildx-action@v3.0.0
      
      - name: Build Docker image
        run: make docker-build

      - name: Push Docker Image
        run: docker tag latest jayaramrcdac/amf && docker push jayaramrcdac/amf
          
  
  lint:
    name: lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: latest
          args: -v --config ./.golangci.yml

  license-check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: reuse lint
        uses: fsfe/reuse-action@v2

  fossa-check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: FOSSA scan
        uses: fossa-contrib/fossa-action@v3
        with:
          fossa-api-key: 0c3bbcdf20e157bbd487dae173751b28

  unit-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Unit tests
        run: go test ./...
